# Generated by Django 6.0.2 on 2026-02-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_id",
            field=models.CharField(
                editable=False, max_length=10, primary_key=True, serialize=False
            ),
        ),
        migrations.AlterUniqueTogether(
            name="attendance",
            unique_together={("employee", "date")},
        ),
    ]
