# Generated by Django 6.0.2 on 2026-02-09 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0002_alter_employee_employee_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
