# Generated by Django 6.0.2 on 2026-02-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_management", "0003_employee_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendance",
            name="created_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
